# Generated by Django 3.2 on 2022-10-24 07:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_group_post_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='follower',
            new_name='Follow',
        ),
    ]
